### ISSUE TITLE
ega schema in json format?

### ISSUE THREAD

**Issue by mshadbolt** [EbiEga/ega-metadata-schema#22]
Hello

Not sure if this is the right place to ask this question (feel free to point me elsewhere if it isn't).

I am trying to wrap my head around the various ways of submitting to the EGA programmatically via the API. My understanding is this can be done using *either* xml or json formatted text.

I have seen that there are a couple of json schemas in this repo, but they don't extend to all the object types required for an EGA submission (e.g. dataset, sample ). 

I have found the full set of XML schemas in the ENA repo here: https://github.com/enasequence/schema/tree/master/src/main/resources/uk/ac/ebi/ena/sra/schema

And the guide to formatting json for EGA submissions here: https://ega-archive.org/submission/programmatic_submissions/json-message-format

But I am wondering whether there either already exist formal json schema for all the various EGA/ENA objects and if so, if you could point me toward them?

Or if not, is there a plan to create and make these available or should I just be working from XML schemas in order to understand how to form valid json for submissions?

Many thanks for any insights you can offer.

**Comment by jorizci** [comment]
Hi Marion,

This repository is a work in progress for a future version of the metadata schema and we do not project to have it finished before the end of the year as all the metadata/submission aspect of the EGA is on a redesign phase. The XML definition at ENA repository is the most complete definition that you can get to create a submission programatically through webin. For more concrete instructions please contact ega helpdesk through: helpdesk@ega-archive.org as they do not usually read the github issues.

Regards and happy to see you.

**Comment by mshadbolt** [comment]
ok great, thanks for the speedy response and thanks for clarifying, I will get in contact with helpdesk if I have any further questions.

Hope all is well at ebi :)
